services:
  cruds.api.processor.form:
    class: ScayTrase\Api\Cruds\Adaptors\Symfony\FormProcessor
    abstract: true
    arguments:
    - "@form.factory"

  cruds.api.processor.mapped_entity_form_factory:
    class: ScayTrase\Api\Cruds\Adaptors\Symfony\MappedEntityFormFactory
    arguments:
    - "@form.factory"
    - "@cruds.property_mapper"

  cruds.api.processor.auto_form:
    class: ScayTrase\Api\Cruds\Adaptors\Symfony\AutoFormProcessor
    arguments:
    - "@form.factory"
    - "@cruds.api.processor.mapped_entity_form_factory"

  cruds.type_guesser.phpdoc:
    class: ScayTrase\Api\Cruds\Adaptors\Symfony\PhpDocTypeGuesser
    arguments:
    - "@annotations.reader"
    tags:
    - { name: form.type_guesser }
