services:
  cruds.api.jms.property_mapper:
    class: ScayTrase\Api\Cruds\Adaptors\Jms\JmsPropertyMapper
    arguments:
    - "@jms_serializer.metadata_factory"

  cruds.jms_serializer:
    class: ScayTrase\Api\Cruds\Adaptors\Jms\JmsSerializerAdapter
    arguments:
    - "@jms_serializer.serializer"
